=== mohamet003/JAXB/jaxb1/xml-resources/jaxb/films/films.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
                elementFormDefault="qualified">

<xs:element name="films">

<xs:complexType>
	<xs:sequence>
		<xs:element name="film" type="filmType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

</xs:element>

<xs:complexType name="filmType">
	<xs:sequence>
	<xs:element name="nom" type="xs:string" />
	<xs:element name="nationalite" type="xs:string" />
	<xs:element name="realisateur" type="xs:string" />
	<xs:element name="genre" type="genreType" />
	<xs:element name="exploitation" type="exploitationType" />
	<xs:element name="acteurs" type="acteursType" />
	<xs:element name="duree" type="dureeType" />
	<xs:element name="scenario" type="xs:string" />
	</xs:sequence>
	<xs:attribute name="sortie" type="xs:gYear" />
	<xs:attribute name="visa" type="xs:string" />
</xs:complexType>

<xs:simpleType name="genreType">
		<xs:restriction base="xs:string">
				<xs:enumeration value="aventure" />
				<xs:enumeration value="policier" />
				<xs:enumeration value="documentaire" />
		</xs:restriction>
</xs:simpleType>

<xs:complexType name="exploitationType">
	<xs:sequence>
	<xs:element name="sortie_en_salle" type="xs:string" />
	<xs:element name="nbr_entrees" type="xs:string" />
	<xs:element name="nbr_salles" type="xs:string" />
	<xs:element name="pays" type="paysType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="acteursType">
	<xs:sequence>
		<xs:element name="acteur" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dureeType">
	<xs:sequence>
		<xs:element name="heures" type="xs:string" />
		<xs:element name="minutes" type="xs:string" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="paysType">
	<xs:sequence>
		<xs:element name="nom" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== mohamet003/JAXB/jaxb1/films.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<films
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/Users/mohametkone/NetBeansProjects/JAXB/films.xsd'>

    <film sortie="2005" visa="114089">
        <nom>king kong</nom>
        <nationalite>americain</nationalite>
        <realisateur>Peter Jackson</realisateur>
        <genre>aventure</genre>
        <exploitation>
            <sortie_en_salle>mercredi 14 decembre 2005</sortie_en_salle>
            <nbr_entrees>2838759</nbr_entrees>
            <nbr_salles>547</nbr_salles>
            <pays>
                <nom>Allemagne</nom>
                <nom>Angleterre</nom>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>Peter Jackson</acteur>
            <acteur>Naomi Watts</acteur>
            <acteur>Jack Black</acteur>
            <acteur>Adrien Brody</acteur>
        </acteurs>
        <duree>
            <heures>3</heures>
            <minutes>8</minutes>
        </duree>
        <scenario>
            NewYork, 1993. Artiste de music hall à la rue, Ann Darrow rencontre l'audacieux explorateur/realisateur Carl Denham. Ce dernier rêve de terminer son film inacheve, mais nourrit surtout la folle ambition d'être le premier à decouvrir le secret de la mysterieuse Skull Island. Il va entraîner Ann dans sa perilleuse aventure...
        </scenario>
    </film>
    <film sortie="2004" visa="114090">
        <nom>Massacre à la tronconneuse</nom>
        <nationalite>français</nationalite>
        <realisateur>Michel Idalgo</realisateur>
        <genre>documentaire</genre>
        <exploitation>
            <sortie_en_salle>jeudi 3 mars 2004</sortie_en_salle>
            <nbr_entrees>283862</nbr_entrees>
            <nbr_salles>134</nbr_salles>
            <pays>
                <nom>Italie</nom>
                <nom>Espagne</nom>
                <nom>Allemagne</nom>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>Roberto Iganco</acteur>
            <acteur>Jack Black</acteur>
            <acteur>Paolo Rossi</acteur>
        </acteurs>
        <duree>
            <heures>2</heures>
            <minutes>2</minutes>
        </duree>
        <scenario>
            Rio, 1956. Paoli Vinci, jeune ouvrier artisan vitrier, arpente les rues de Rio à la recherche de clients. Il rencontre Suzanne la vendeuse de glace du quartier qui vient de se faire devaliser par Jojo le cireur de chaussures...
        </scenario>
    </film>
    <film sortie="2006" visa="114091">
        <nom>Pars loin et reviens tard</nom>
        <nationalite>français</nationalite>
        <realisateur>Jose Garcia</realisateur>
        <genre>policier</genre>
        <exploitation>
            <sortie_en_salle>mercredi 6 fevrier 2006</sortie_en_salle>
            <nbr_entrees>1245986</nbr_entrees>
            <nbr_salles>456</nbr_salles>
            <pays>
                <nom>Angleterre</nom>
                <nom>Espagne</nom>
                <nom>Belgique</nom>
            </pays>
        </exploitation>
        <acteurs>
            <acteur>Jose Garcia</acteur>
            <acteur>Nicolas Cage</acteur>
            <acteur>Noemie Campbell</acteur>
            <acteur>Nathalie Baye</acteur>
        </acteurs>
        <duree>
            <heures>1</heures>
            <minutes>45</minutes>
        </duree>
        <scenario>
            L'inspecteur Rinaldo vit mal sa separation avec Cindy Lu et broie du noir au commissariat. Son adjoint Pascal Fenet joue les intermediaires et s'attire les foudres de l'inspecteur...
        </scenario>
    </film>
</films>
